// The native peer. One command per run:
//   describe            the self-description text
//   hash                schema_v, 8 hex digits
//   values [n]          layer/field=value lines after n steps from the initial state (n = 0 or STEPS)
//   frame [n]           hex of the frame after n steps
//   zero                hex of the frame of the all-zero state
//   header              C header for the AVR peer: the frame of the initial state, and the frames it must refuse
//   verify HEX          read HEX (a frame from the AVR peer) and compare with STEPS steps from the initial state
//   json                the initial state as JSON
#include "net2.h"
#include <oneMachine/state/wire.h>
#include <oneMachine/state/face.h>
#include <stdio.h>
#include <string.h>
#include <string>
#include <vector>
#include <stdlib.h>

struct Out { void operator()(char c) { putchar(c); } };
static std::string str(state::Name n) { std::string r; for (unsigned i = 0; n.at(i); i++) r += n.at(i); return r; }
struct Values { std::string cur; void layer(state::Name n) { cur = str(n); }
  template<class T> void operator()(state::Name n, const T& v) {
    printf("%s/%s=", cur.c_str(), str(n).c_str());
    if constexpr (std::is_same<T, bool>::value) printf("%d\n", int(v));
    else if constexpr (state::wcode<T>() & 1) printf("%lld\n", (long long)v); else printf("%llu\n", (unsigned long long)v); } };
struct Locate { const char* want; unsigned off = 0; bool found = false;         // byte offset of a field in the frame body
  void layer(state::Name) {}
  template<class T> void operator()(state::Name n, const T&) { if (!found && str(n) == want) found = true; else if (!found) off += sizeof(T); } };

static Net2 stepped(int n) { Net2 s = initial(), t{}; for (int i = 0; i < n; i++) { t.step(s); s = t; } return s; }
static std::vector<uint8_t> frame(const Net2& s) { uint8_t b[state::wire_size<Net2>()]; uint8_t* e = state::write(s, b); return {b, e}; }
static void hex(const std::vector<uint8_t>& v) { for (uint8_t b : v) printf("%02x", b); }
static void carray(const char* name, const std::vector<uint8_t>& v) {
  printf("static const uint8_t %s[] ONEMACHINE_STATE_ROM = {", name); for (size_t i = 0; i < v.size(); i++) printf("%s%u", i ? "," : "", v[i]); printf("};\n"); }

int main(int argc, char** argv) {
  std::string c = argc > 1 ? argv[1] : "";
  int n = argc > 2 ? atoi(argv[2]) : 0;
  Out o;
  if (c == "describe") state::describe<Net2>(o);
  else if (c == "hash") printf("%08x\n", (unsigned)state::schema_v<Net2>);
  else if (c == "values") { Values v; stepped(n).each(v); }
  else if (c == "frame") { hex(frame(stepped(n))); putchar('\n'); }
  else if (c == "zero") { hex(frame(Net2{})); putchar('\n'); }
  else if (c == "json") { state::json(initial(), o); putchar('\n'); }
  else if (c == "header") {
    auto good = frame(initial()); auto badhash = good; badhash[0] ^= 0x01;
    auto badbool = good; Locate l{"flag"}; initial().each(l); badbool[4 + l.off] = 2;
    printf("// generated by host_peer header\n#include <oneMachine/state/state.h>\n");
    carray("IN_GOOD", good); carray("IN_BADHASH", badhash); carray("IN_BADBOOL", badbool);
    printf("static const unsigned IN_N = %zu;\n", good.size());
  }
  else if (c == "verify" && argc > 2) {
    std::vector<uint8_t> b; for (const char* p = argv[2]; p[0] && p[1]; p += 2) { unsigned x; sscanf(p, "%2x", &x); b.push_back(uint8_t(x)); }
    Net2 got{}; state::Status st = state::read(got, b.data(), unsigned(b.size()));
    Net2 want = stepped(STEPS); bool same = st == state::Status::Ok && frame(got) == frame(want);
    printf("verify: status %d, %s\n", int(st), same ? "equal to the native state after the steps" : "DIFFERENT");
    return same ? 0 : 1;
  }
  else { fprintf(stderr, "usage: host_peer describe|hash|values [n]|frame [n]|json|header|verify HEX\n"); return 2; }
  return 0;
}
